#!/usr/bin/env node
/* Verifies a built artifact against UX-SPEC.md §23.4 and the gates in §25.6.
 *
 * The panel discards a template it cannot parse and serves its own page with no
 * error anywhere, so every one of these checks stands in for a failure that is
 * otherwise silent in production.
 *
 *   node tools/verify.mjs [artifact]
 */

import { readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Script } from 'node:vm';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/* The 22 keys SubService puts in the view model (RESEARCH.md §4). A field
   outside this set renders empty and would never announce itself. */
const FIELDS = new Set([
  'sId', 'enabled', 'isOnline', 'download', 'upload', 'total', 'used', 'remained',
  'expire', 'lastOnline', 'downloadByte', 'uploadByte', 'totalByte', 'subUrl',
  'subJsonUrl', 'subClashUrl', 'subTitle', 'subSupportUrl', 'announce', 'links',
  'emails', 'datepicker',
]);

const MIN_BYTES = 40 * 1024;

/* Deliberately blunt: on a page whose URL is itself a credential, a mechanical
   check is more reliable than review attention. */
const FORBIDDEN = [
  [/\binnerHTML\b/, 'innerHTML'],
  [/\bouterHTML\b/, 'outerHTML'],
  [/insertAdjacentHTML/, 'insertAdjacentHTML'],
  [/\beval\s*\(/, 'eval('],
  [/\bnew\s+Function\s*\(/, 'new Function('],
  [/document\s*\.\s*write/, 'document.write'],
  [/sourceMappingURL/, 'a source map reference'],
  [/\blocalhost\b/, 'localhost'],
  [/\b127\.0\.0\.1\b/, 'a loopback address'],
  [/[A-Za-z]:\\[A-Za-z. ]/, 'a developer machine path'],
  [/row-dev/, 'the development fixture selector'],
  [/jsdelivr|unpkg|cdnjs|googleapis|gstatic|\bcdn\./i, 'a CDN reference'],
  [/chatgpt|openai|anthropic|copilot|generated by ai|as an ai\b/i, 'AI attribution'],
];

/* The SVG namespace is a constant, not a fetch. Everything else that looks
   remote has to justify itself. */
const ALLOWED_REMOTE = new Set(['http://www.w3.org/2000/svg']);

/* Listed numerically on purpose: an invisible character typed into a source
   file is the hazard, so the guard against it must not contain one. Persian
   needs U+200C, which the catalogues carry as a JSON escape instead. */
const INVISIBLE = new Set([
  0x00ad, 0x061c, 0x180e, 0x200b, 0x200c, 0x200d, 0x200e, 0x200f,
  0x202a, 0x202b, 0x202c, 0x202d, 0x202e, 0x2060, 0x2061, 0x2062,
  0x2063, 0x2064, 0x2066, 0x2067, 0x2068, 0x2069, 0xfeff,
]);
const SKIP_DIRS = new Set(['node_modules', 'out', 'build', '.git', 'template']);
const SCAN_EXT = /\.(?:mjs|js|css|html|json|go|md|sh)$/;

let failed = 0;

function pass(label, note) {
  process.stdout.write(`ok   ${label}${note ? `  ${note}` : ''}\n`);
}

function fail(label, detail) {
  failed += 1;
  process.stdout.write(`FAIL ${label}\n       ${detail}\n`);
}

function check(label, detail) {
  if (detail) fail(label, detail);
  else pass(label);
}

/* §23.4: a truncated write and a failed inlining step both leave a file that
   still opens in a browser, so shape is checked before content. */
function checkShape(html, bytes) {
  check('artifact is a whole document',
    bytes < MIN_BYTES ? `only ${(bytes / 1024).toFixed(1)} KiB, expected at least 40 KiB`
      : !html.startsWith('<!doctype html>') ? 'does not begin with a doctype'
        : !html.includes('<html') ? 'no <html'
          : !html.trimEnd().endsWith('</html>') ? 'does not end with </html>'
            : '');

  const marker = html.match(/\/\*__[A-Z][A-Z0-9_]*__\*\//);
  check('every build marker was substituted', marker ? `${marker[0]} is still there` : '');

  const styles = (html.match(/<style>/g) || []).length;
  const scripts = (html.match(/<script(?: |>)/g) || []).length;
  check('everything is inlined',
    styles !== 1 || scripts !== 3 ? `expected 1 style and 3 script elements, found ${styles} and ${scripts}` : '');
}

/* §23.4: the installer rewrites the branding block in place. Losing a marker
   turns the next install into a silent no-op. */
function checkBranding(html) {
  const open = (html.match(/\/\* row:branding \*\//g) || []).length;
  const close = (html.match(/\/\* row:branding end \*\//g) || []).length;
  if (open !== 1 || close !== 1) {
    fail('branding block is substitutable', `found ${open} opening and ${close} closing markers`);
    return { serviceName: '', logo: '' };
  }

  const block = html.slice(html.indexOf('/* row:branding */'), html.indexOf('/* row:branding end */'));
  const field = (name) => {
    const m = block.match(new RegExp(`${name}\\s*:\\s*(['"])((?:[^'"\\\\]|\\\\.)*)\\1`));
    return m ? m[2] : null;
  };
  const serviceName = field('serviceName');
  const logo = field('logo');
  if (serviceName === null || logo === null || field('supportUrl') === null) {
    fail('branding block is substitutable', 'serviceName, supportUrl or logo is missing from the block');
    return { serviceName: '', logo: '' };
  }
  pass('branding block is substitutable', serviceName ? `service name ${JSON.stringify(serviceName)}` : 'unbranded build');

  check('logo is inlined or absent',
    logo && !/^data:image\/(?:png|jpeg|gif|webp|svg\+xml);base64,/.test(logo)
      ? `logo is not an inlined data URI: ${logo.slice(0, 40)}` : '');
  return { serviceName, logo };
}

/* §23.4: an unbalanced action is a parse error, and a mistyped field is worse
   than an error because it renders as nothing at all. */
function checkActions(html) {
  const actions = html.match(/\{\{[^{}]*\}\}/g) || [];
  check('template actions are present', actions.length === 0 ? 'no Go actions found at all' : '');

  let depth = 0;
  let underflow = false;
  for (const action of actions) {
    if (/^\{\{-?\s*(?:if|range|with|define|block)\b/.test(action)) depth += 1;
    else if (/^\{\{-?\s*end\s*-?\}\}$/.test(action)) {
      depth -= 1;
      if (depth < 0) underflow = true;
    }
  }
  check('template actions balance',
    underflow ? 'an {{ end }} appears before its action' : depth !== 0 ? `${depth} action(s) left open` : '');

  const unknown = new Set();
  for (const action of actions) {
    for (const m of action.matchAll(/\.([A-Za-z_][A-Za-z0-9_]*)/g)) {
      if (!FIELDS.has(m[1])) unknown.add(m[1]);
    }
  }
  check('every field is in the panel view model',
    unknown.size ? `not in the 22-key model: ${[...unknown].join(', ')}` : '');
}

/* Concatenating modules into one scope is the build's only real trick, and a
   syntax error in the result would only surface as a page that never boots.
   Compiling without running is enough to catch it. */
function checkScripts(html) {
  const blocks = [...html.matchAll(/<script(?<attrs>[^>]*)>(?<body>[\s\S]*?)<\/script>/g)];
  let broken = '';
  let json = 'the i18n island is missing';

  for (const block of blocks) {
    const { attrs, body } = block.groups;
    if (attrs.includes('application/json')) {
      try {
        const cats = JSON.parse(body.split('\\u003c').join('<'));
        const langs = Object.keys(cats);
        const sizes = langs.map((l) => Object.keys(cats[l]).length);
        json = langs.length !== 5 ? `${langs.length} languages, expected 5`
          : new Set(sizes).size !== 1 ? `catalogues differ in size: ${sizes.join(', ')}` : '';
      } catch (err) {
        json = `the i18n island does not parse: ${err.message}`;
      }
      continue;
    }
    try {
      new Script(body);
    } catch (err) {
      broken = `${err.message}`;
    }
  }

  check('inline scripts compile', broken);
  check('locale catalogues are intact', json);
}

/* §25.6: the artifact must reach for nothing and mention nobody. Branding is
   cut out first, because an administrator's own support URL and logo are the
   one legitimate source of remote-looking text in an installed file. */
function checkGates(html) {
  const body = html.replace(/\/\* row:branding \*\/[\s\S]*?\/\* row:branding end \*\//, '');

  const found = [];
  for (const [pattern, name] of FORBIDDEN) {
    const m = body.match(pattern);
    if (m) found.push(`${name} (${JSON.stringify(m[0].slice(0, 40))})`);
  }
  check('no forbidden constructs', found.join('; '));

  const remote = new Set();
  for (const m of body.matchAll(/https?:\/\/[^\s"'`)\\]*/g)) {
    if (!ALLOWED_REMOTE.has(m[0])) remote.add(m[0]);
  }
  check('no remote references', remote.size ? [...remote].slice(0, 5).join(', ') : '');
}

/* The catalogues and the bidi isolates are the two places invisible characters
   belong, and both express them as escapes. One typed into a source file is
   unreviewable, so it is a build failure rather than a style question. */
function checkSources() {
  const hits = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        if (!SKIP_DIRS.has(entry.name)) walk(join(dir, entry.name));
        continue;
      }
      if (!SCAN_EXT.test(entry.name)) continue;
      const path = join(dir, entry.name);
      const text = readFileSync(path, 'utf8');
      let line = 1;
      for (const ch of text) {
        if (ch === '\n') line += 1;
        else if (INVISIBLE.has(ch.codePointAt(0))) {
          hits.push(`${relative(ROOT, path)}:${line} U+${ch.codePointAt(0).toString(16).toUpperCase().padStart(4, '0')}`);
        }
      }
    }
  };
  walk(join(ROOT, 'src'));
  walk(join(ROOT, 'tools'));
  walk(join(ROOT, 'tests'));
  check('sources carry no invisible characters', hits.slice(0, 6).join(', '));
}

function main(argv) {
  const target = argv[0] ? resolve(process.cwd(), argv[0]) : join(ROOT, 'template', 'index.html');
  let html;
  try {
    html = readFileSync(target, 'utf8');
  } catch (err) {
    process.stderr.write(`cannot read ${target}: ${err.message}\nBuild it first: node tools/build.mjs\n`);
    process.exit(1);
  }

  process.stdout.write(`${relative(ROOT, target) || target}\n`);
  checkShape(html, statSync(target).size);
  checkBranding(html);
  checkActions(html);
  checkScripts(html);
  checkGates(html);
  checkSources();

  process.stdout.write(`\n${failed === 0 ? 'all checks passed' : `${failed} check(s) failed`}\n`);
  process.exit(failed === 0 ? 0 : 1);
}

main(process.argv.slice(2));
